name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: webadmin
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            echo ${{ secrets.DROPLET_PASSWORD }} | sudo -S systemctl stop kestrel-mockinterviews.service
            cd /var/www/sp2023-mis421-mockinterviews/
            git pull
            dotnet restore
            cd sp2023-mis421-mockinterviews/
            dotnet ef database update --verbose --context UserDataDbContext --connection ${{ secrets.USERS_CONNECTION_STRING }}
            dotnet ef database update --verbose --context MockInterviewDataDbContext --connection ${{ secrets.SIGNUPS_CONNECTION_STRING }}
            cd ..
            dotnet build &&
            echo ${{ secrets.DROPLET_PASSWORD }} | sudo -S systemctl start kestrel-mockinterviews.service

      - name: Exit SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: webadmin
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: exit
