name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: webadmin
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /var/www/sp2023-mis421-mockinterviews/
            git pull
            dotnet build &&
            echo ${{ secrets.DROPLET_PASSWORD }} | sudo -S systemctl restart kestrel-mockinterviews.service

      - name: Exit SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: webadmin
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: exit
          
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP2 }}
          username: webadmin
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /var/www/sp2023-mis421-mockinterviews/
            git pull
            dotnet build &&
            echo ${{ secrets.DROPLET_PASSWORD }} | sudo -S systemctl restart kestrel-mockinterviews.service

      - name: Exit SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP2 }}
          username: webadmin
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: exit
